server:
  port: 10001
spring:
  application:
    name: auth-silo
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.macgrant-platform.test/realms/kyc
      client:
        registration:
          auth-silo:
            provider: keycloak
            client-id: auth-silo
            client-secret: d63cc0f7dd2f4c3179e3e615284886e6d34f1ef9bb9a4d73
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: https://keycloak.macgrant-platform.test/realms/kyc
keycloak:
  base-url: https://keycloak.macgrant-platform.test/admin/realms/kyc

user-silo:
  base-url: https://user-silo.macgrant-platform.test

logging:
  level:
    org.springframework.security: TRACE